loss_function: binary
layers:
  - type: InputLayer
    input_size: 30
  - type: Dense
    input_size: 30
    output_size: 24
    kernel_initializer: he
  - type: Sigmoid
  - type: Dense
    input_size: 24
    output_size: 24
    kernel_initializer: he
  - type: Sigmoid
  - type: Dense
    input_size: 24
    output_size: 24
    kernel_initializer: he
  - type: Sigmoid
  - type: Dense
    input_size: 24
    output_size: 2
    kernel_initializer: he
  - type: Softmax
